# Site settings
title: nonie 
tag_text: 
description:  
url: "https://www.nonie.io"
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
